// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bin_collection_weeks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBinCollectionWeek = `-- name: CreateBinCollectionWeek :one
INSERT INTO bin_collection_weeks (
  id,
  created_at,
  updated_at,
  week_start_date,
  zone
)
VALUES (
  ?1,
  DATETIME('now', 'utc'),
  DATETIME('now', 'utc'),
  ?2,
  ?3
)
RETURNING id, created_at, updated_at, week_start_date, zone
`

type CreateBinCollectionWeekParams struct {
	ID            uuid.UUID
	WeekStartDate time.Time
	Zone          string
}

func (q *Queries) CreateBinCollectionWeek(ctx context.Context, arg CreateBinCollectionWeekParams) (BinCollectionWeek, error) {
	row := q.db.QueryRowContext(ctx, createBinCollectionWeek, arg.ID, arg.WeekStartDate, arg.Zone)
	var i BinCollectionWeek
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeekStartDate,
		&i.Zone,
	)
	return i, err
}
