// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: streets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createStreet = `-- name: CreateStreet :one
INSERT INTO streets (id, created_at, updated_at, name, suburb_id)
VALUES (
  ?1,
  DATETIME('now', 'utc'),
  DATETIME('now', 'utc'),
  ?2,
  ?3
)
RETURNING id, created_at, updated_at, name, suburb_id
`

type CreateStreetParams struct {
	ID       uuid.UUID
	Name     string
	SuburbID uuid.UUID
}

func (q *Queries) CreateStreet(ctx context.Context, arg CreateStreetParams) (Street, error) {
	row := q.db.QueryRowContext(ctx, createStreet, arg.ID, arg.Name, arg.SuburbID)
	var i Street
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.SuburbID,
	)
	return i, err
}
