// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: suburbs.sql

package database

import (
	"context"
)

const createSuburb = `-- name: CreateSuburb :one
INSERT INTO suburbs (id, created_at, updated_at, name)
VALUES (
  ?1,
  DATETIME('now', 'utc'),
  DATETIME('now', 'utc'),
  ?2
)
RETURNING id, created_at, updated_at, name
`

type CreateSuburbParams struct {
	ID   interface{}
	Name string
}

func (q *Queries) CreateSuburb(ctx context.Context, arg CreateSuburbParams) (Suburb, error) {
	row := q.db.QueryRowContext(ctx, createSuburb, arg.ID, arg.Name)
	var i Suburb
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
